// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jaam8/pkg/txman"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTxman creates a new instance of MockTxman. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTxman(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTxman {
	mock := &MockTxman{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTxman is an autogenerated mock type for the Txman type
type MockTxman struct {
	mock.Mock
}

type MockTxman_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTxman) EXPECT() *MockTxman_Expecter {
	return &MockTxman_Expecter{mock: &_m.Mock}
}

// Do provides a mock function for the type MockTxman
func (_mock *MockTxman) Do(ctx context.Context, h txman.Handler, opts ...txman.TxOption) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, h, opts)
	} else {
		tmpRet = _mock.Called(ctx, h)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, txman.Handler, ...txman.TxOption) error); ok {
		r0 = returnFunc(ctx, h, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTxman_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockTxman_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - ctx context.Context
//   - h txman.Handler
//   - opts ...txman.TxOption
func (_e *MockTxman_Expecter) Do(ctx interface{}, h interface{}, opts ...interface{}) *MockTxman_Do_Call {
	return &MockTxman_Do_Call{Call: _e.mock.On("Do",
		append([]interface{}{ctx, h}, opts...)...)}
}

func (_c *MockTxman_Do_Call) Run(run func(ctx context.Context, h txman.Handler, opts ...txman.TxOption)) *MockTxman_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 txman.Handler
		if args[1] != nil {
			arg1 = args[1].(txman.Handler)
		}
		var arg2 []txman.TxOption
		var variadicArgs []txman.TxOption
		if len(args) > 2 {
			variadicArgs = args[2].([]txman.TxOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockTxman_Do_Call) Return(err error) *MockTxman_Do_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTxman_Do_Call) RunAndReturn(run func(ctx context.Context, h txman.Handler, opts ...txman.TxOption) error) *MockTxman_Do_Call {
	_c.Call.Return(run)
	return _c
}
