// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package txman

import (
	"context"

	"github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPostgres creates a new instance of MockPostgres. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostgres(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostgres {
	mock := &MockPostgres{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPostgres is an autogenerated mock type for the Postgres type
type MockPostgres struct {
	mock.Mock
}

type MockPostgres_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostgres) EXPECT() *MockPostgres_Expecter {
	return &MockPostgres_Expecter{mock: &_m.Mock}
}

// BeginTx provides a mock function for the type MockPostgres
func (_mock *MockPostgres) BeginTx(ctx context.Context, opts pgx.TxOptions) (pgx.Tx, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 pgx.Tx
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.TxOptions) (pgx.Tx, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.TxOptions) pgx.Tx); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Tx)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pgx.TxOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPostgres_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type MockPostgres_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx context.Context
//   - opts pgx.TxOptions
func (_e *MockPostgres_Expecter) BeginTx(ctx interface{}, opts interface{}) *MockPostgres_BeginTx_Call {
	return &MockPostgres_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx, opts)}
}

func (_c *MockPostgres_BeginTx_Call) Run(run func(ctx context.Context, opts pgx.TxOptions)) *MockPostgres_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgx.TxOptions
		if args[1] != nil {
			arg1 = args[1].(pgx.TxOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostgres_BeginTx_Call) Return(tx pgx.Tx, err error) *MockPostgres_BeginTx_Call {
	_c.Call.Return(tx, err)
	return _c
}

func (_c *MockPostgres_BeginTx_Call) RunAndReturn(run func(ctx context.Context, opts pgx.TxOptions) (pgx.Tx, error)) *MockPostgres_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}
